import pandas as pd
file = pd.read_csv("WindPower.csv")
print("First 5 Rows")
print(file.head())
print("\nDataset Shape")
print(file.shape)
print("\nColumn Names")
print(file.columns)
print("\nDataset Information")
print(file.info())
print("\nMissing Values")
print(file.isnull().sum())
print("\nStatistical Summary")
print(file.describe())
print("\nDuplicate Rows")
print(file.duplicated().sum())
